@endpoint = http://localhost:{{$dotenv PORT}}

####################################################
#                       Valid
####################################################

### signup
POST {{ endpoint }}/signup
Content-Type: application/json

{
    "email": "toto@tata.com",
    "first_name": "toto",
    "last_name": "tata",
    "password": "TotoTata!123",
    "passwordConfirm": "TotoTata!123"
}


### profil
GET {{ endpoint }}/user/1/profil

### create card
POST {{ endpoint }}/user/1/cards/today
Content-Type: application/json

{
    "text": "carte teste 2",
    "moodId": 4
}

### find card
GET {{ endpoint }}/user/1/cards/1

####################################################
#                       Errors
####################################################

### Already exists
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "toto@tata.com",
    "first_name": "toto",
    "last_name": "tata",
    "password": "TotoTata!123",
    "passwordConfirm": "TotoTata!123"
}

### Error props
POST http://localhost:3000/signup
Content-Type: application/json

{
    "emai": "toto@tata.com",
    "first_name": "toto",
    "last_name": "tata",
    "password": "TotoTata!123",
    "passwordConfirm": "TotoTata!123"
}

### 404
GET {{ endpoint }}/user/2/profi