@endpoint = http://localhost:{{$dotenv PORT}}

####################################################
#                       Valid
####################################################

### signup
POST {{ endpoint }}/signup
Content-Type: application/json

{
    "email": "bonjour@tata.com",
    "first_name": "toto",
    "last_name": "tata",
    "password": "TotoTata!123",
    "passwordConfirm": "TotoTata!123"
}


### profil
GET {{ endpoint }}/user/3/profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0b3RvQHRhdGEuY29tIiwiZmlyc3RfbmFtZSI6InRvdG8iLCJsYXN0X25hbWUiOiJ0YXRhIiwicGFzc3dvcmQiOiIkMmIkMTAkWkRuTmJ1S0NucmRUSU1vVy90aktZT0Nha293TXZFYnFiN0FLSW5pdlh2RmQwUVFKNW9JVEMiLCJpbWFnZSI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMDFUMTM6NDQ6MDYuODM0WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY0NjIxMDY4MiwiZXhwIjoxNjQ2MjEyNDgyfQ.zBp4O67Hbr1p0oay3ZNMOTCofRTzb99Wtj2SYgI92pg

### utilisateur
POST {{ endpoint }}/login
Content-Type: application/json

{
    "email": "bonjour@tata.com",
    "password": "TotoTata!123"
}

### utilisateur logout 
POST {{ endpoint }}/logout


### refresh token route

### utilisateur
POST {{ endpoint }}/api/refreshtoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0b3RvQHRhdGEuY29tIiwiZmlyc3RfbmFtZSI6InRvdG8iLCJsYXN0X25hbWUiOiJ0YXRhIiwicGFzc3dvcmQiOiIkMmIkMTAkWkRuTmJ1S0NucmRUSU1vVy90aktZT0Nha293TXZFYnFiN0FLSW5pdlh2RmQwUVFKNW9JVEMiLCJpbWFnZSI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMDFUMTM6NDQ6MDYuODM0WiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY0NjIxMDY0OCwiZXhwIjoxNjQ2MjEyNDQ4fQ.3DyKD89z7PrnmjPZ16g35InEoBz8119kmL_j7_uZ3XI

### create card
POST {{ endpoint }}/user/1/cards/today
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJib25qb3VyQHRhdGEuY29tIiwiZmlyc3RfbmFtZSI6InRvdG8iLCJsYXN0X25hbWUiOiJ0YXRhIiwicGFzc3dvcmQiOiIkMmIkMTAkRnRXdDJUWU04SXRvVVg5THE2QjRSZTc2QkZSZW1Hc0MvbURqRlJZVDNaOXh5cDIwTmwzc2kiLCJpbWFnZSI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMDJUMTM6NTQ6MTguNjUzWiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY0NjIyOTI2NywiZXhwIjoxNjQ2MjMxMDY3fQ.SpucK1J-oIYkPSBIZ92FUhxcG5y8E-7VEzVv8WCa_Qw
Content-Type: application/json

{
    "text": "carte teste 3"
}

### update card
PATCH {{ endpoint }}/user/1/cards/today
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJib25qb3VyQHRhdGEuY29tIiwiZmlyc3RfbmFtZSI6InRvdG8iLCJsYXN0X25hbWUiOiJ0YXRhIiwicGFzc3dvcmQiOiIkMmIkMTAkRnRXdDJUWU04SXRvVVg5THE2QjRSZTc2QkZSZW1Hc0MvbURqRlJZVDNaOXh5cDIwTmwzc2kiLCJpbWFnZSI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMDJUMTM6NTQ6MTguNjUzWiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY0NjIyOTI2NywiZXhwIjoxNjQ2MjMxMDY3fQ.SpucK1J-oIYkPSBIZ92FUhxcG5y8E-7VEzVv8WCa_Qw
Content-Type: application/json

{
    "text": "Première",
    "video": "essai patch"
}

### find card
GET {{ endpoint }}/user/1/cards/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJib25qb3VyQHRhdGEuY29tIiwiZmlyc3RfbmFtZSI6InRvdG8iLCJsYXN0X25hbWUiOiJ0YXRhIiwicGFzc3dvcmQiOiIkMmIkMTAkRnRXdDJUWU04SXRvVVg5THE2QjRSZTc2QkZSZW1Hc0MvbURqRlJZVDNaOXh5cDIwTmwzc2kiLCJpbWFnZSI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMDJUMTM6NTQ6MTguNjUzWiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY0NjIyOTI2NywiZXhwIjoxNjQ2MjMxMDY3fQ.SpucK1J-oIYkPSBIZ92FUhxcG5y8E-7VEzVv8WCa_Qw

####################################################
#                       Errors
####################################################

### Already exists
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "toto@tata.com",
    "first_name": "toto",
    "last_name": "tata",
    "password": "TotoTata!123",
    "passwordConfirm": "TotoTata!123"
}

### Error props
POST http://localhost:3000/signup
Content-Type: application/json

{
    "emai": "toto@tata.com",
    "first_name": "toto",
    "last_name": "tata",
    "password": "TotoTata!123",
    "passwordConfirm": "TotoTata!123"
}

### 404
GET {{ endpoint }}/user/2/profi