@endpoint = http://localhost:{{$dotenv PORT}}

####################################################
#                       Valid
####################################################

### signup
POST {{ endpoint }}/signup
Content-Type: application/json

{
    "email": "bonjours@tata.com",
    "first_name": "toto",
    "last_name": "tata",
    "password": "TotoTata!123",
    "passwordConfirm": "TotoTata!123"
}


### profil

GET {{ endpoint }}/user/1/profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0b3RvQHRhdGEuY29tIiwiZmlyc3RfbmFtZSI6InRvdG8iLCJsYXN0X25hbWUiOiJ0YXRhIiwicGFzc3dvcmQiOiIkMmIkMTAkM3dnaC9VL3NsSEIybVNJNEZJcGZxT3BxZjhjcEJCdkUuMTQ3c3JDNzc3bVhidVJTaDBSREMiLCJpbWFnZSI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMDJUMDk6MTg6MDQuNDEzWiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY0NjIzMDcxMSwiZXhwIjoxNjQ2MjMyNTExfQ.vr6pFZgNS2ePaMXjgxXg-kWTfdeRJLIiEjWo7lIGb0c

### update profil
PATCH {{ endpoint }}/user/1/profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0b3RvQHRhdGEuY29tIiwiZmlyc3RfbmFtZSI6InRvdG8iLCJsYXN0X25hbWUiOiJ0YXRhIiwicGFzc3dvcmQiOiIkMmIkMTAkM3dnaC9VL3NsSEIybVNJNEZJcGZxT3BxZjhjcEJCdkUuMTQ3c3JDNzc3bVhidVJTaDBSREMiLCJpbWFnZSI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMDJUMDk6MTg6MDQuNDEzWiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY0NjIzMzA0MSwiZXhwIjoxNjQ2MjM0ODQxfQ._uPXVKE4z9R5n_2PPGGEOtrzfvT_SaEiH8MPcSvpxf0
Content-Type: application/json

{
    "first_name": "didi",
    "last_name": "dadada"
}

### utilisateur
POST {{ endpoint }}/login
Content-Type: application/json

{
    "email": "bonjours@tata.com",
    "password": "TotoTata!123"
}

### utilisateur logout 
POST {{ endpoint }}/logout


### refresh token route

### utilisateur
POST {{ endpoint }}/api/refreshtoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJib25qb3Vyc0B0YXRhLmNvbSIsImZpcnN0X25hbWUiOiJ0b3RvIiwibGFzdF9uYW1lIjoidGF0YSIsInBhc3N3b3JkIjoiJDJiJDEwJHdsZkNzdGRvTndXR3UuTjBnRExRVHVmdUhJcHBQRS94UHVhVHRCUFczZ0hQb0Y4NE1BQXlpIiwiaW1hZ2UiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIyLTAzLTAzVDEwOjAyOjE3LjU2MFoiLCJ1cGRhdGVkX2F0IjpudWxsLCJpYXQiOjE2NDYzMDE3NDMsImV4cCI6MTY0NjMwMzU0M30.uMDjq2YcWiRIFrBEPskay7RDmcW7xto16J_N4naWDCk

### create card

POST {{ endpoint }}/user/1/cards/today
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJib25qb0B0YXRhLmNvbSIsImZpcnN0X25hbWUiOiJ0b3RvIiwibGFzdF9uYW1lIjoidGF0YSIsInBhc3N3b3JkIjoiJDJiJDEwJEhnZXZXVHVjeXFYVW9aMFFwVlBHZU9lWGpGWFpydUU4RjV4aE5IQ2FrdG40UnBtYVd6RTVPIiwiaW1hZ2UiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIyLTAzLTAyVDE0OjQ5OjI2LjM3MFoiLCJ1cGRhdGVkX2F0IjpudWxsLCJpYXQiOjE2NDYyMzI1NzEsImV4cCI6MTY0NjIzNDM3MX0.wyEosZ4RRUTyHdALb0iOz6fzs2Q5YgYXvOey_wqwsQg

Content-Type: application/json

{
    "text": "carte teste 3",
    "moodLabel": "happy"
}

### update card
PATCH {{ endpoint }}/user/3/cards/today
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJib25qb3Vyc0B0YXRhLmNvbSIsImZpcnN0X25hbWUiOiJ0b3RvIiwibGFzdF9uYW1lIjoidGF0YSIsInBhc3N3b3JkIjoiJDJiJDEwJHdsZkNzdGRvTndXR3UuTjBnRExRVHVmdUhJcHBQRS94UHVhVHRCUFczZ0hQb0Y4NE1BQXlpIiwiaW1hZ2UiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIyLTAzLTAzVDEwOjAyOjE3LjU2MFoiLCJ1cGRhdGVkX2F0IjpudWxsLCJpYXQiOjE2NDYzMDE3NDMsImV4cCI6MTY0NjMwMzU0M30.uMDjq2YcWiRIFrBEPskay7RDmcW7xto16J_N4naWDCk
Content-Type: application/json

{
    "text": "Bonjour"
}

### find card
GET {{ endpoint }}/user/1/cards/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0b3RvQHRhdGEuY29tIiwiZmlyc3RfbmFtZSI6InRvdG8iLCJsYXN0X25hbWUiOiJ0YXRhIiwicGFzc3dvcmQiOiIkMmIkMTAkM3dnaC9VL3NsSEIybVNJNEZJcGZxT3BxZjhjcEJCdkUuMTQ3c3JDNzc3bVhidVJTaDBSREMiLCJpbWFnZSI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMDJUMDk6MTg6MDQuNDEzWiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY0NjIxNzY5MCwiZXhwIjoxNjQ2MjE5NDkwfQ.Tuz5miXIRBNlpXTS9Su-1Tm86cpKqN0SQCnfPyvRSmE


### dashboard
GET {{ endpoint }}/user/1/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0b3RvQHRhdGEuY29tIiwiZmlyc3RfbmFtZSI6InRvdG8iLCJsYXN0X25hbWUiOiJ0YXRhIiwicGFzc3dvcmQiOiIkMmIkMTAkM3dnaC9VL3NsSEIybVNJNEZJcGZxT3BxZjhjcEJCdkUuMTQ3c3JDNzc3bVhidVJTaDBSREMiLCJpbWFnZSI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjItMDMtMDJUMDk6MTg6MDQuNDEzWiIsInVwZGF0ZWRfYXQiOm51bGwsImlhdCI6MTY0NjIyNjgwNywiZXhwIjoxNjQ2MjI4NjA3fQ.JtRE6kBO7BMcuOtPHXnpYN-BjIhRM7Y9hSQ586pKljk
####################################################
#                       Errors
####################################################

### Already exists
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "toto@tata.com",
    "first_name": "toto",
    "last_name": "tata",
    "password": "TotoTata!123",
    "passwordConfirm": "TotoTata!123"
}

### Error props
POST http://localhost:3000/signup
Content-Type: application/json

{
    "emai": "toto@tata.com",
    "first_name": "toto",
    "last_name": "tata",
    "password": "TotoTata!123",
    "passwordConfirm": "TotoTata!123"
}

### 404
GET {{ endpoint }}/user/2/profi





### signup
POST https://dyl-api.herokuapp.com/signup
Content-Type: application/json

{
    "email": "moi@supermoi.com",
    "first_name": "toto",
    "last_name": "tata",
    "password": "TotoTata!123",
    "passwordConfirm": "TotoTata!123"
}